class SUCCESS_MSGS:
    GREETING_SAVED = "greetings saved"
    SIGNUP_SUCCESSFUL = "Signup start successfully"


class ERROR_MSGS:
    INTERNAL_SERVER_ERROR = "Internal server error"
    GREETING_SAVED_UNSUCESSFUL = "GREETING SAVED UNSUCCESSFUL"
    PHONE_NUMBER_REQUIRED = "PHONE NUMBER REQUIRED"
    SIGNUP_FAILED = "Signup start failed"
    PHONE_EMAIL_REQUIRED = "Phone or Email is required"
    USER_ALREADY_EXIST = "User already exists"


class ERROR_TYPES:
    DATA_NOT_FOUND = "DATA_NOT_FOUND"
    BAD_REQUEST = "BAD_REQUEST"
    ALREADY_EXISTS = "ALREADY_EXISTS"
    FORBIDDEN = "FORBIDDEN"
    SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    SOCKET_ERROR = "SOCKET_ERROR"
    INVALID_MOVE = "invalidMove"
